service:
  name: nginx
  namespace: default
  port: 80
  protocol: TCP
  targetPort: 80
  app: nginx
  type: NodePort

nginx:
  name: nginx
  namespace: default
  label: nginx
  replicas: 2
  image: nginx
  imagePullPolicy: Always
  containerPort: 80
  memory: 256Mi
  cpu: 100m

targetGroupBinding:
  name: nginx
  namespace: default
  port: 80
  targetGroupARN: kustomized
  targetType: ip