apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  namespace: {{ .Values.service.namespace}}
spec:
  ports:
    - port: {{ .Values.service.port}}
      protocol: {{ .Values.service.protocol}}
      targetPort: {{ .Values.service.targetPort}}
  selector:
    app: {{ .Values.service.app}}
  type: {{ .Values.service.type}}